# prison layout #4 - 5x4
[people]
guard = [0, 0]
prisoner = [1, 0]

[room]
width = 5
height = 4
rotation = 0
exit = [3, 3]

walls = [
    [[0, 0], [1, 0]],
    [[1, 0], [1, 1]],
    [[3, 1], [3, 2]],
    [[2, 3], [3, 3]],
]