[people]
guard = [0, 7]
prisoner = [4, 6]

[room]
width = 7
height = 8
rotation = 0
exit = [6, 7]

walls = [
    [[0, 1], [1, 1]],
    [[0, 2], [1, 2]],
    [[0, 3], [1, 3]],
    [[1, 2], [1, 3]],

    [[2, 0], [2, 1]],
    [[3, 0], [3, 1]],

    [[2, 3], [2, 4]],
    [[3, 3], [3, 4]],
    [[1, 4], [2, 4]],
    [[2, 4], [2, 5]],
    [[3, 4], [3, 5]],

    [[4, 1], [5, 1]],
    [[4, 2], [5, 2]],
    [[4, 3], [5, 3]],
    [[4, 4], [5, 4]],
    [[4, 5], [5, 5]],
    [[5, 5], [5, 6]],
    [[5, 6], [6, 6]],

    [[5, 1], [6, 1]],
    [[5, 2], [6, 2]],
    [[5, 3], [6, 3]],
    [[5, 4], [6, 4]],
]