[package]
name = "houdini-cli"
version = "0.1.0"
authors = ["Mel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
houdini-solver = { path = "../solver" }
toml = "0.5"